gitCredentials: 
    d1apjnksmas101: git-credentails
    papjnksmas101: git-credentails  

appName:
    provider-portal-app-test: 
        projectName: dev
        repoName: repo1
        commonApp: 'N'
        scriptId: Jenkinsfile-apps  
        permission: 
            - user1
            - user1
            - user2

    hashing-utility:
        projectName: dev 
        repoName: multi_branch_poc
        commonApp: 'Y'
        scriptId: Jenkinsfile
        permission: 
            - user1
            - user3
   

Application_name:
    application1:
        name: provider-portal-app
        dd: provider_portal
        playbook: pp.yml
    application2:
        name: queuemanager
        dd: queue_manager
        playbook: qm.yml
    application3:
        name: app1
        dd: rules
        playbook: play.yml

#features
deploy:
    provider-portal-app:
        display: myansible-job
        war_version: 1.27.20
        repoName: repo3
        env: q1
        Artifact_location: release, hotfix
        playbook: playbook
        ansible_node: ansi@server:22
        emailRecipientList: 
            - test@gmail.com
        accessPermissions:
        Team1: 
            - user1
            - test
            - user4
            

#To Notify 
email_notifiy:
    accessPermissions:
        Team1: 
            - user1
            - test
            - test
        Team2:
            - user2
            - user4
    emailRecipientList:
        Team1:
            - user1
            - reciptents
      